title: About the Foundation For Public Code
url: https://about.publiccode.net
permalinks: pretty

include:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

plugins:
  - jekyll-remote-theme
remote_theme: publiccodenet/jekyll-theme
