title: About the Foundation For Public Code
permalinks: pretty

include:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

plugins:
  - jekyll-remote-theme
  - jekyll-feed
remote_theme: publiccodenet/jekyll-theme

# Exclude the `vendor` folder created by Travis
exclude:
  - vendor
